/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:b03b6d109cccca649004c2521c4528f0:481e4aaaa09ed003483d2a7fc257dd1d:af633d31c3393ae9fd430138abbd6857$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class tpSprites
	{
		public const string EnemyEyes_idle_0 = "EnemyEyes/idle/0";
		public const string EnemyEyes_idle_1 = "EnemyEyes/idle/1";
		public const string EnemyEyes_idle_2 = "EnemyEyes/idle/2";
		public const string EnemyEyes_idle_3 = "EnemyEyes/idle/3";
		public const string EnemyEyes_idle_4 = "EnemyEyes/idle/4";
	}
}