/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:ff8b5c12ac03844fcef94095fb715d54:d17118a06c68109036756f8f82708af5:af633d31c3393ae9fd430138abbd6857$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class tpSprites
	{
		public const string EnemyBullet_idle_0 = "EnemyBullet/idle/0";
		public const string EnemyBullet_idle_1 = "EnemyBullet/idle/1";
		public const string EnemyEyes_idle_0 = "EnemyEyes/idle/0";
		public const string EnemyEyes_idle_1 = "EnemyEyes/idle/1";
		public const string EnemyEyes_idle_2 = "EnemyEyes/idle/2";
		public const string EnemyEyes_idle_3 = "EnemyEyes/idle/3";
		public const string EnemyEyes_idle_4 = "EnemyEyes/idle/4";
		public const string EnemyEyes_pop_0 = "EnemyEyes/pop/0";
		public const string EnemyEyes_pop_1 = "EnemyEyes/pop/1";
		public const string EnemyEyes_pop_2 = "EnemyEyes/pop/2";
		public const string EnemyEyes_pop_3 = "EnemyEyes/pop/3";
		public const string EnemyEyes_pop_4 = "EnemyEyes/pop/4";
		public const string EnemyEyes_pop_5 = "EnemyEyes/pop/5";
		public const string EnemyPinks_idle_0 = "EnemyPinks/idle/0";
		public const string EnemyPinks_idle_1 = "EnemyPinks/idle/1";
		public const string EnemyPinks_idle_2 = "EnemyPinks/idle/2";
		public const string EnemyPinks_idle_3 = "EnemyPinks/idle/3";
		public const string EnemyPinks_idle_4 = "EnemyPinks/idle/4";
		public const string EnemyPinks_pop_0 = "EnemyPinks/pop/0";
		public const string EnemyPinks_pop_1 = "EnemyPinks/pop/1";
		public const string EnemyPinks_pop_2 = "EnemyPinks/pop/2";
		public const string EnemyPinks_pop_3 = "EnemyPinks/pop/3";
		public const string EnemyPinks_pop_4 = "EnemyPinks/pop/4";
		public const string EnemyPinks_pop_5 = "EnemyPinks/pop/5";
		public const string EnemySaucer_idle_0 = "EnemySaucer/idle/0";
		public const string EnemySaucer_idle_1 = "EnemySaucer/idle/1";
		public const string EnemySaucer_idle_2 = "EnemySaucer/idle/2";
		public const string EnemySaucer_idle_3 = "EnemySaucer/idle/3";
		public const string EnemySaucer_pop_0 = "EnemySaucer/pop/0";
		public const string EnemySaucer_pop_1 = "EnemySaucer/pop/1";
		public const string EnemySaucer_pop_2 = "EnemySaucer/pop/2";
		public const string EnemySaucer_pop_3 = "EnemySaucer/pop/3";
		public const string EnemySquid_idle_0 = "EnemySquid/idle/0";
		public const string EnemySquid_idle_1 = "EnemySquid/idle/1";
		public const string EnemySquid_idle_2 = "EnemySquid/idle/2";
		public const string EnemySquid_idle_3 = "EnemySquid/idle/3";
		public const string EnemySquid_idle_4 = "EnemySquid/idle/4";
		public const string EnemySquid_pop_0 = "EnemySquid/pop/0";
		public const string EnemySquid_pop_1 = "EnemySquid/pop/1";
		public const string EnemySquid_pop_2 = "EnemySquid/pop/2";
		public const string EnemySquid_pop_3 = "EnemySquid/pop/3";
		public const string EnemySquid_pop_4 = "EnemySquid/pop/4";
		public const string EnemySquid_pop_5 = "EnemySquid/pop/5";
		public const string Player_fire_0 = "Player/fire/0";
		public const string Player_fire_1 = "Player/fire/1";
		public const string Player_idle_0 = "Player/idle/0";
		public const string Player_idle_1 = "Player/idle/1";
	}
}