/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:91473e0b20e12c013dc99ed674cdf8bb:481e4aaaa09ed003483d2a7fc257dd1d:e76696c31d8f8d2b79caa79fd6323a72$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class tpSprites
	{
		public const string EnemyEyes_idle1 = "EnemyEyes/idle1";
		public const string EnemyEyes_idle2 = "EnemyEyes/idle2";
		public const string EnemyEyes_idle3 = "EnemyEyes/idle3";
		public const string EnemyEyes_idle4 = "EnemyEyes/idle4";
		public const string EnemyEyes_idle5 = "EnemyEyes/idle5";
	}
}